version: 2

sources:
  - name: products
    database: steadfast-icon-336102
    schema: dbt_jandrade
    tables:
     - name: products

models:
  - name: stg_customers
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null

  - name: stg_orders
    columns:
      - name: order_id
        tests:
          - unique
          - not_null
      - name: status
        tests:
          - accepted_values:
              values: ['placed', 'shipped', 'completed', 'return_pending', 'returned']

  - name: stg_payments
    columns:
      - name: payment_id
        tests:
          - unique
          - not_null
      - name: payment_method
        tests:
          - accepted_values:
              values: ['credit_card', 'coupon', 'bank_transfer', 'gift_card']
  - name: stg_products
    columns:
      - name: Product_ID
        tests:
         - unique
         - not_null
      - name: Sale_Price
        tests:
         - unique
         - not_null

